apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: transactiondb
    app.kubernetes.io/component: transactiondb
    app.kubernetes.io/instance: transactiondb
  name: transactiondb
  namespace: payroll
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: transactiondb
  strategy: {}
  template:
    metadata:
      labels:
        deployment: transactiondb
    spec:
      containers:
      - env:
        - name: POSTGRESQL_DATABASE
          value: transaction
        - name: POSTGRESQL_PASSWORD
          value: password
        - name: POSTGRESQL_USER
          value: transaction
        image: registry.redhat.io/rhel8/postgresql-13:1
        name: transactiondb
        ports:
        - containerPort: 5432
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: transactiondb
    app.kubernetes.io/component: transactiondb
    app.kubernetes.io/instance: transactiondb
  name: transactiondb
  namespace: payroll
spec:
  ports:
  - name: 5432-tcp
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    deployment: transactiondb