version: '3'

services:
  postgres:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password

  keycloak:
      image: quay.io/keycloak/keycloak:legacy
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: password
      ports:
        - 8080:8080
      depends_on:
        - postgres

  zookeeper:
    image: quay.io/debezium/zookeeper:1.8
    restart: always
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888

  kafka:
    image: quay.io/debezium/kafka:1.8
    restart: always
    ports:
      - 9092:9092
      - 9093:9093
    depends_on:
      - zookeeper
    environment:
      ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:29092,PLAINTEXT_HOST://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092

  connect:
    image: quay.io/debezium/connect:1.8
    ports:
     - 8088:8083
    links:
     - kafka
     - employeeDB
    environment:
      BOOTSTRAP_SERVERS: kafka:29092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses

  menuDB:
      image: postgres
      volumes:
        - menuDB_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: menu
        POSTGRES_USER: menu
        POSTGRES_PASSWORD: password
      ports:
        - 5433:5432

  paymentDB:
      image: postgres
      volumes:
        - paymentDB_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: payment
        POSTGRES_USER: payment
        POSTGRES_PASSWORD: password
      ports:
        - 5434:5432

  userProfileDB:
      image: postgres
      volumes:
        - userProfileDB_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: user_profile
        POSTGRES_USER: user_profile
        POSTGRES_PASSWORD: password
      ports:
        - 5435:5432

  employeeDB:
      image: postgres
      volumes:
        - employeeDB_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: employee
        POSTGRES_USER: employee
        POSTGRES_PASSWORD: password
      ports:
        - 5436:5432
      command: [ "postgres", "-c", "wal_level=logical" ]

volumes:
  postgres_data:
      driver: local
  menuDB_data:
      driver: local
  paymentDB_data:
      driver: local
  userProfileDB_data:
      driver: local
  employeeDB_data:
      driver: local