apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: application
    repoURL: https://github.com/Tanakan/openshift-cluster
    targetRevision: HEAD
