apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: keycloak
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    app: sso
  namespace: sso
spec:
  instances: 1
  externalAccess:
    enabled: true