kind: KeycloakClient
apiVersion: keycloak.org/v1alpha1
metadata:
  name: 3scale-admin
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    app: sso
  namespace: sso
spec:
  realmSelector:
    matchLabels:
      app: sso
  client:
    clientId: 3scale-admin
    clientAuthenticatorType: client-secret
    serviceAccountsEnabled: true