resources:
  #3scale
- 3scale/namespace.yaml
- 3scale/operatorgroup.yaml
- 3scale/subscription.yaml

  #amq
- amq/namespace.yaml
- amq/operatorgroup.yaml
- amq/subscription.yaml

  #canteen
- canteen/namespace.yaml
- canteen/operatorgroup.yaml
- canteen/subscription.yaml

  #payroll
- payroll/namespace.yaml

  #people
- people/namespace.yaml

  #sso
- sso/namespace.yaml
- sso/operatorgroup.yaml
- sso/subscription.yaml

  #tools
- tools/namespace.yaml
