kind: NFSProvisioner
apiVersion: cache.jhouse.com/v1alpha1
metadata:
  name: nfs
  namespace: 3scale
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  scForNFS: nfs
  scForNFSPvc: gp2
  storageSize: 1G