kind: APIManager
apiVersion: apps.3scale.net/v1alpha1
metadata:
  name: apimanager
  namespace: 3scale
spec:
  wildcardDomain: apps.cluster-c8p96.c8p96.sandbox675.opentlc.com
  system:
    fileStorage: 
      persistentVolumeClaim:
        storageClassName: ocs-storagecluster-cephfs