apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: cluster
    repoURL: https://github.com/Tanakan/openshift-cluster
    targetRevision: HEAD
  syncPolicy:
    automated: {}
