apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: paymentdb
    app.kubernetes.io/component: paymentdb
    app.kubernetes.io/instance: paymentdb
  name: paymentdb
  namespace: canteen
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: paymentdb
  strategy: {}
  template:
    metadata:
      labels:
        deployment: paymentdb
    spec:
      containers:
      - env:
        - name: POSTGRESQL_DATABASE
          value: payment
        - name: POSTGRESQL_PASSWORD
          value: password
        - name: POSTGRESQL_USER
          value: payment
        image: registry.redhat.io/rhel8/postgresql-13:1
        name: paymentdb
        ports:
        - containerPort: 5432
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: paymentdb
    app.kubernetes.io/component: paymentdb
    app.kubernetes.io/instance: paymentdb
  name: paymentdb
  namespace: canteen
spec:
  ports:
  - name: 5432-tcp
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    deployment: paymentdb