apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: menudb
    app.kubernetes.io/component: menudb
    app.kubernetes.io/instance: menudb
  name: menudb
  namespace: canteen
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: menudb
  strategy: {}
  template:
    metadata:
      labels:
        deployment: menudb
    spec:
      containers:
      - env:
        - name: POSTGRESQL_DATABASE
          value: menu
        - name: POSTGRESQL_PASSWORD
          value: password
        - name: POSTGRESQL_USER
          value: menu
        image: registry.redhat.io/rhel8/postgresql-13:1
        name: menudb
        ports:
        - containerPort: 5432
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: menudb
    app.kubernetes.io/component: menudb
    app.kubernetes.io/instance: menudb
  name: menudb
  namespace: canteen
spec:
  ports:
  - name: 5432-tcp
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    deployment: menudb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: paymentdb
    app.kubernetes.io/component: paymentdb
    app.kubernetes.io/instance: paymentdb
  name: paymentdb
  namespace: canteen
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: paymentdb
  strategy: {}
  template:
    metadata:
      labels:
        deployment: paymentdb
    spec:
      containers:
      - env:
        - name: POSTGRESQL_DATABASE
          value: payment
        - name: POSTGRESQL_PASSWORD
          value: password
        - name: POSTGRESQL_USER
          value: payment
        image: registry.redhat.io/rhel8/postgresql-13:1
        name: paymentdb
        ports:
        - containerPort: 5432
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: paymentdb
    app.kubernetes.io/component: paymentdb
    app.kubernetes.io/instance: paymentdb
  name: paymentdb
  namespace: canteen
spec:
  ports:
  - name: 5432-tcp
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    deployment: paymentdb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: transactiondb
    app.kubernetes.io/component: transactiondb
    app.kubernetes.io/instance: transactiondb
  name: transactiondb
  namespace: payroll
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: transactiondb
  strategy: {}
  template:
    metadata:
      labels:
        deployment: transactiondb
    spec:
      containers:
      - env:
        - name: POSTGRESQL_DATABASE
          value: transaction
        - name: POSTGRESQL_PASSWORD
          value: password
        - name: POSTGRESQL_USER
          value: transaction
        image: registry.redhat.io/rhel8/postgresql-13:1
        name: transactiondb
        ports:
        - containerPort: 5432
          protocol: TCP
---
kind: Service
metadata:
  labels:
    app: transactiondb
    app.kubernetes.io/component: transactiondb
    app.kubernetes.io/instance: transactiondb
  name: transactiondb
  namespace: payroll
spec:
  ports:
  - name: 5432-tcp
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    deployment: transactiondb
