apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: operatorgroup
  namespace: canteen
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  targetNamespaces:
  - canteen