apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: fuse-online
  namespace: canteen
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  channel: stable
  name: fuse-online
  source: redhat-operators
  sourceNamespace: openshift-marketplace