kind: Syndesis
apiVersion: syndesis.io/v1beta3
metadata:
  name: app
  namespace: canteen
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  addons:
    jaeger:
      enabled: true
    ops:
      enabled: false
    publicApi:
      enabled: false
    todo:
      enabled: false