kind: APIManager
apiVersion: apps.3scale.net/v1alpha1
metadata:
  name: apimanager
  namespace: 3scale
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  wildcardDomain: <wildcardDomain>
  system:
    fileStorage: 
      persistentVolumeClaim:
        storageClassName: ocs-storagecluster-cephfs