
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: 3scale-operator
  namespace: 3scale
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  channel: threescale-2.11
  name: 3scale-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace